name: fashionclub
description: "fashionclub appilcation app for rent clothes"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  dartz: ^0.10.1
  url_launcher: ^6.3.1
  lottie: ^3.3.1
  rxdart: ^0.28.0
  carousel_slider: ^5.0.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.3.5
  device_info_plus: ^11.2.1
  flutter_phoenix: ^1.1.1
  carousel_indicator: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #dart run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png 
  fullscreen: true
  android: true
  ios: true
  android_12:
    image: assets/images/splash_logo.png 
    image_dark: assets/images/splash_logo.png 
    color: "#000000"
    color_dark: "#000000"
  android_gravity: "center"
  
flutter:
  uses-material-design: true
  assets: 
    - assets/images/splash_logo.png 
    - assets/images/boarding.svg
    - assets/images/soldLine.svg
    - assets/images/hollowLine.svg
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/loading.json
    - assets/json/success.json
    - assets/json/instagram-logo.json
    - assets/json/twitter-logo.json
    - assets/json/whatsapp-button.json
    - assets/json/contact-email.json
    - assets/images/menu.svg
    - assets/images/rentLine.svg
    - assets/images/aboutUs1.jpg
    - assets/images/aboutUs2.jpg
    - assets/images/aboutUs3.jpg
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/Cairo-Black.ttf
           weight: 700
         - asset: assets/fonts/Cairo-Bold.ttf
           weight: 700
         - asset: assets/fonts/Cairo-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Cairo-Medium.ttf
           weight: 500
         - asset: assets/fonts/Cairo-Regular.ttf
           weight: 400
         - asset: assets/fonts/Cairo-Light.ttf
           weight: 300  
